[tool.poetry]
name = "pg-es-fdw"
version = "0.11.1"
description = "Connect PostgreSQL and Elastic Search with this Foreign Data Wrapper"
authors = ["Matthew Franglen <matthew@franglen.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/matthewfranglen/postgres-elasticsearch-fdw"
repository = "https://github.com/matthewfranglen/postgres-elasticsearch-fdw"
keywords = ["postgresql", "postgres", "elasticsearch", "es", "fdw"]

[tool.poetry.urls]
download ="https://github.com/matthewfranglen/postgres-elasticsearch-fdw/archive/0.11.1.zip"

[tool.poetry.dependencies]
elasticsearch = [
    { version = ">=0,<1", python = "*", optional = true },
    { version = ">=1,<2", python = "*", optional = true },
    { version = ">=2,<3", python = "*", optional = true },
    { version = ">=5,<6", python = "*", optional = true },
    { version = ">=6,<7", python = ">=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <4", optional = true },
    { version = ">=7,<8", python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <4", optional = true },
    { version = ">=8,<9", python = ">=3.6, <4", optional = true },
]

[tool.poetry.dev-dependencies]
black = { version = "^22.8.0", python = ">=3.6" }
pylint = { version = "^2.15.2", python = ">=3.7.2" }
pytest = { version = "^7.1.3", python = ">=3.7" }
sh = "^1.12.14"
docker-compose = "^1.25.4"
psycopg2 = "^2.8.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
